### ISSUE TITLE
File has no sequences defined

### ISSUE THREAD

**Issue by Lewis-Gallagher** [qiaseq/qiaseq-dna#26]
Hi, I'm really interested in using your tool.  I've been having trouble just getting the smCounter2 variant caller to work on it's own so I've moved to running the whole pipeline instead.  

I've downloaded the docker image and am running the test exactly as described in the readme (inputting v2.params.txt and v2 as arguments) however I'm getting the following error

```
2019-02-13 12:38:58.428 umi_filter: starting...
2019-02-13 12:38:58.586 ('# of primers:', 651)
2019-02-13 12:38:58.601 Traceback (most recent call last):
2019-02-13 12:38:58.601   File "/srv/qgen/code/qiaseq-dna/run_qiaseq_dna.py", line 160, in <module>
2019-02-13 12:38:58.611 run((readSet,paramFile,vc))
2019-02-13 12:38:58.612   File "/srv/qgen/code/qiaseq-dna/run_qiaseq_dna.py", line 55, in run
2019-02-13 12:38:58.613 core.umi_filter.run(cfg, bamFileIn)
2019-02-13 12:38:58.613   File "/srv/qgen/code/qiaseq-dna/core/umi_filter.py", line 81, in run
2019-02-13 12:38:58.614 bam = pysam.Samfile(bamFileIn, "rb")
2019-02-13 12:38:58.614   File "pysam/calignmentfile.pyx", line 333, in pysam.calignmentfile.AlignmentFile.__cinit__ (pysam/calignmentfile.c:4808)
2019-02-13 12:38:58.660   File "pysam/calignmentfile.pyx", line 574, in pysam.calignmentfile.AlignmentFile._open (pysam/calignmentfile.c:7530)
2019-02-13 12:38:58.661 ValueError
2019-02-13 12:38:58.662 :
2019-02-13 12:38:58.663 file has no sequences defined (mode='rb') - is it SAM/BAM format? Consider opening with check_seq=True
```

It may also be worth mentioning that I am very new to docker so it could be something I'm overlooking

Thanks

**Comment by rpadmanabhan** [comment]
That does seem strange. Could you take a look at the intermediate summary file *.prep.summary.txt and post the contents here ?
It looks like the *.align.bam is empty or has only unmapped reads which should not happen. Could you  verify that ?
Also could you post your exact python and docker run command ?

**Comment by Lewis-Gallagher** [comment]
Intermediate summary: 
```
3935302 read fragments total
21188   read fragments dropped, less than 40 bp
```

And the *.aign.bam is empty.

The commands I ran are as follows
```
$ sudo docker run -it -v /Users/lgallagher/Software/smcounter2-docker/:/mnt/qiaseq-run/ rpadmanabhan9/qiaseq-dna:pipeline
$ root@5c7f8b65d43c:/data# cd /srv/qgen/code/
$ cd /srv/qgen/code/
$ git clone --recursive https://github.com/qiaseq/qiaseq-dna.git
$ cd /mnt/qiaseq-run/
$ cp /srv/qgen/code/qiaseq-dna/run_sm_counter_v2.params.txt ./
$ python /srv/qgen/code/qiaseq-dna/run_qiaseq_dna.py run_sm_counter_v2.params.txt v2 single NEB_S2 > run.log 2>&1 & 
```

I just followed the instructions [here](https://github.com/qiaseq/qiaseq-dna#docker-image-for-third-party-dependencies)

**Comment by rpadmanabhan** [comment]
Thanks, I think something wrong in the alignment step. Could you post the contents of this file : *.align.bwa.log

**Comment by Lewis-Gallagher** [comment]
The align.bwa.log file is empty, as well as the align.samtools.log, .umi_filter.alignments.txt and .umi_filter.no-primer.txt

**Comment by rpadmanabhan** [comment]
Is there anything in run.log ?

**Comment by Lewis-Gallagher** [comment]
```
gzip: stdout: Broken pipe
================================================================
Program: CD-HIT, V4.7 (+OpenMP), Apr 20 2018, 18:02:45
Command:
         /srv/qgen/bin/downloads/cd-hit-v4.6.8-2017-1208/cd-hit-est
         -i /srv/qgen/example/DHS-101Z.primers.txt.fasta -o
         /srv/qgen/example/DHS-101Z.primers.txt.clusters.temp

Started: Wed Feb 13 12:29:12 2019
================================================================
                            Output                              
----------------------------------------------------------------
total seq: 651
longest and shortest : 43 and 20
Total letters: 19499
Sequences have been sorted

Approximated minimal memory consumption:
Sequence        : 0M
Buffer          : 1 X 12M = 12M
Table           : 1 X 16M = 16M
Miscellaneous   : 4M
Total           : 33M

Table limit with the given memory limit:
Max number of representatives: 4000000
Max number of word counting entries: 95856808

^Mcomparing sequences from          0  to        651

      651  finished        651  clusters

Apprixmated maximum memory consumption: 33M
writing new database
writing clustering information
program completed !

Total CPU time 0.07
Killed
run.log (END)
```

**Comment by rpadmanabhan** [comment]
That 'Killed' at the end suggests some step ran out of memory. It is most likely bwa , since the trimming step completed (based on the *.prep.summary file). I am not sure why that did not throw a non zero return code, which would then have been caught in the python script.

How much cpu and memory do you have on your machine ? 
By default, all the cpu cores are used in the pipeline, you could modify the numCores parameter in the params file to a smaller value to keep the memory consumption lower.

**Comment by Lewis-Gallagher** [comment]
I see, I'll give that a try.  I am running on 32GB and a 4 core intel cpu.  The numCores variable is set to 0 in the params file.  I'll change it to 1 and see what happens.  Thanks.

**Comment by Lewis-Gallagher** [comment]
Getting exactly the same errors as before:
```
2019-02-14 11:41:18.726 prep: starting read prep - trimming ends and UMI extraction
2019-02-14 11:41:19.119 prep: check for wrong sequencing primer using first 1,000 reads: % wrong is 0.0
2019-02-14 11:44:22.016  i=0; while read chrom pos strand primer; do echo ">"$i; echo $primer|tr -d '
2019-02-14 11:44:22.019 ';  i=$(($i+1)); done < /srv/qgen/example/DHS-101Z.primers.txt > /srv/qgen/example/DHS-101Z.primers.txt.fasta;
2019-02-14 11:44:23.128 prep: starting parallel trimming batches
2019-02-14 11:58:10.620 prep: completed parallel trimming batches
2019-02-14 11:58:28.811 prep: done
2019-02-14 11:58:28.812 align: starting read alignment
2019-02-14 11:58:46.660 align: done aligning reads to genome, bam file: NEB_S2.align.bam
2019-02-14 11:58:46.687 umi_filter: starting...
2019-02-14 11:58:46.704 ('# of primers:', 651)
2019-02-14 11:58:46.723 Traceback (most recent call last):
2019-02-14 11:58:46.723   File "/srv/qgen/code/qiaseq-dna/run_qiaseq_dna.py", line 160, in <module>
2019-02-14 11:58:46.728 run((readSet,paramFile,vc))
2019-02-14 11:58:46.729   File "/srv/qgen/code/qiaseq-dna/run_qiaseq_dna.py", line 55, in run
2019-02-14 11:58:46.729 core.umi_filter.run(cfg, bamFileIn)
2019-02-14 11:58:46.729   File "/srv/qgen/code/qiaseq-dna/core/umi_filter.py", line 81, in run
2019-02-14 11:58:46.730 bam = pysam.Samfile(bamFileIn, "rb")
2019-02-14 11:58:46.730   File "pysam/calignmentfile.pyx", line 333, in pysam.calignmentfile.AlignmentFile.__cinit__ (pysam/calignmentfile.c:4808)
2019-02-14 11:58:46.741   File "pysam/calignmentfile.pyx", line 574, in pysam.calignmentfile.AlignmentFile._open (pysam/calignmentfile.c:7530)
2019-02-14 11:58:46.742 ValueError
2019-02-14 11:58:46.743 :
2019-02-14 11:58:46.743 file has no sequences defined (mode='rb') - is it SAM/BAM format? Consider opening with check_seq=True
NEB_S2.run_log.2019.02.14_11.41.18.txt (END)
```

**Comment by rpadmanabhan** [comment]
Hmm, sorry this is a little hard to debug, not really sure what is going on. 32 GB should be more than enough for alignment. 8-10 GB is good enough.

Could you run this command inside the docker container , when in the /srv/qgen/example directory : 
`/opt/conda/bin/bwa mem -C -t 64 /srv/qgen/data/genome/ucsc.hg19.fa NEB_S2.prep.R1.fastq NEB_S2.prep.R2.fastq 2>NEB_S2.align.bwa.log | /srv/qgen/bin/samtools-1.5/bin/samtools view -1 -@ 64 -  1> NEB_S2.align.bam 2> NEB_S2.align.samtools.log`

 This will let us know if you are able to get the .align.bam file.

**Comment by Lewis-Gallagher** [comment]
The align.bam and log file turn out empty too.  I decided to go ahead and run the smCounter2 docker image on my data and everything seems to be working just fine.  So at least that's something!

**Comment by rpadmanabhan** [comment]
Well glad atleast that worked out. So both log files are empty ? 
For your data, were you able to successfully align the fastq files on this same machine ?

I also have the following suggestions to try :  Take ~ 1000 sequences from the prep.fastq files and align them using the above command see if that gives you a non-empty bam

**Comment by lxhuang7** [comment]
I encountered the same error when using 2Gb memory. When increasing the memory to 12Gb for the container the pipeline runs successfully for the example files.

**Comment by SPPearce** [comment]
I'm getting a very similar issue, even for taking the first 1000 sequences, when running on a Macbook Pro with 16Gb RAM. The log file:

2019-05-01 11:16:58.008 Processed : 250 reads
2019-05-01 11:16:58.013 prep: done
2019-05-01 11:16:58.013 align: starting read alignment
2019-05-01 11:17:13.483 align: done aligning reads to genome, bam file: NEB_S2.align.bam
2019-05-01 11:17:13.565 umi_filter: starting...
2019-05-01 11:17:14.052 ('# of primers:', 651)
2019-05-01 11:17:14.085 Traceback (most recent call last):
2019-05-01 11:17:14.086   File "/srv/qgen/code/qiaseq-dna/run_qiaseq_dna.py", line 203, in <module>
2019-05-01 11:17:14.095 run((readSet,paramFile,vc),tumorNormal = False)
2019-05-01 11:17:14.095   File "/srv/qgen/code/qiaseq-dna/run_qiaseq_dna.py", line 57, in run
2019-05-01 11:17:14.096 core.umi_filter.run(cfg, bamFileIn)
2019-05-01 11:17:14.096   File "/srv/qgen/code/qiaseq-dna/core/umi_filter.py", line 81, in run
2019-05-01 11:17:14.098 bam = pysam.Samfile(bamFileIn, "rb")
2019-05-01 11:17:14.098   File "pysam/calignmentfile.pyx", line 333, in pysam.calignmentfile.AlignmentFile.__cinit__ (pysam/calignmentfile.c:4808)
2019-05-01 11:17:14.160   File "pysam/calignmentfile.pyx", line 574, in pysam.calignmentfile.AlignmentFile._open (pysam/calignmentfile.c:7530)
2019-05-01 11:17:14.163 ValueError
2019-05-01 11:17:14.164 :
2019-05-01 11:17:14.165 file has no sequences defined (mode='rb') - is it SAM/BAM format? Consider opening with check_seq=True

**Comment by lxhuang7** [comment]
You might want to check your docker setting. What’s the memory size for your docker container? By default it’s only 2Gb on my laptop so I increase it to > 8G and it works. HTH.
-Lei


On May 1, 2019, at 6:19 AM, Simon Pearce <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm getting a very similar issue, even for taking the first 1000 sequences, when running on a Macbook Pro with 16Gb RAM. The log file:

2019-05-01 11:16:58.008 Processed : 250 reads
2019-05-01 11:16:58.013 prep: done
2019-05-01 11:16:58.013 align: starting read alignment
2019-05-01 11:17:13.483 align: done aligning reads to genome, bam file: NEB_S2.align.bam
2019-05-01 11:17:13.565 umi_filter: starting...
2019-05-01 11:17:14.052 ('# of primers:', 651)
2019-05-01 11:17:14.085 Traceback (most recent call last):
2019-05-01 11:17:14.086 File "/srv/qgen/code/qiaseq-dna/run_qiaseq_dna.py", line 203, in
2019-05-01 11:17:14.095 run((readSet,paramFile,vc),tumorNormal = False)
2019-05-01 11:17:14.095 File "/srv/qgen/code/qiaseq-dna/run_qiaseq_dna.py", line 57, in run
2019-05-01 11:17:14.096 core.umi_filter.run(cfg, bamFileIn)
2019-05-01 11:17:14.096 File "/srv/qgen/code/qiaseq-dna/core/umi_filter.py", line 81, in run
2019-05-01 11:17:14.098 bam = pysam.Samfile(bamFileIn, "rb")
2019-05-01 11:17:14.098 File "pysam/calignmentfile.pyx", line 333, in pysam.calignmentfile.AlignmentFile.cinit (pysam/calignmentfile.c:4808)
2019-05-01 11:17:14.160 File "pysam/calignmentfile.pyx", line 574, in pysam.calignmentfile.AlignmentFile._open (pysam/calignmentfile.c:7530)
2019-05-01 11:17:14.163 ValueError
2019-05-01 11:17:14.164 :
2019-05-01 11:17:14.165 file has no sequences defined (mode='rb') - is it SAM/BAM format? Consider opening with check_seq=True

**Comment by SPPearce** [comment]
Thanks Lei, that is probably the issue. I have managed to turn it into a singularity container and it works fine on my HPC now.
