### ISSUE TITLE
'function' object has no attribute 'readSetMatchedNormal' error during tumor normal variant filtering step

### ISSUE THREAD

**Issue by lxhuang7** [qiaseq/qiaseq-dna#34]
Hi  Raghavendra, 

I was using your pipeline to perform a variant calling on a pair of tumor-normal samples. 

```
$ python /srv/qgen/code/qiaseq-dna/run_qiaseq_dna.py run_sm_counter_v2.params.tn.txt v2 tumor-normal OV_1580 N_1580 > run.log 2>&1 &
```

Everything went well until I had the following error:

-----------------------------------
```
2019-04-23 08:32:57.098 Traceback (most recent call last):
2019-04-23 08:32:57.098   File "/srv/qgen/code/qiaseq-dna/run_qiaseq_dna.py", line 201, in <module>
2019-04-23 08:32:57.098 run_tumor_normal(readSet,paramFile,vc)
2019-04-23 08:32:57.098   File "/srv/qgen/code/qiaseq-dna/run_qiaseq_dna.py", line 160, in run_tumor_normal
2019-04-23 08:32:57.098 core.tumor_normal.tumorNormalVarFilter(cfg)
2019-04-23 08:32:57.098   File "/srv/qgen/code/qiaseq-dna/core/tumor_normal.py", line 322, in tumorNormalVarFilter
2019-04-23 08:32:57.100 readSetNormal =  cfg.readSetMatchedNormal
2019-04-23 08:32:57.100 AttributeError
2019-04-23 08:32:57.100 :
2019-04-23 08:32:57.100 'function' object has no attribute 'readSetMatchedNormal'
```
-----------------------------------

I traced the error back to the following lines in ```run_qiaseq_dna.py```:
```
   if vc == 'v2': # use new TN filter
        print("--"*20)
        cfg = core.run_config.run(tumor,paramFile)
        core.tumor_normal.tumorNormalVarFilter(cfg)
        print("--"*20)
   print(dir(cfg)):
['__call__', '__class__', '__closure__', '__code__', '__defaults__', '__delattr__', '__dict__', '__doc__', '__format__', '__get__', '__getattribute__', '__globals__', '__hash__', '__init__', '__module__', '__name__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'bwaDir', 'clinVarFile', 'cosmicFile', 'cutadaptDir', 'dbSnpFile', 'deleteLocalFiles', 'duplex', 'endogenousLenMin', 'func_closure', 'func_code', 'func_defaults', 'func_dict', 'func_doc', 'func_globals', 'func_name', 'genomeFile', 'instrument', 'javaExe', 'multimodal', 'numCores', 'outputDetail', 'pValCutoff', 'platform', 'primer3Bases', 'primerFile', 'quandicoDir', 'readFile1', 'readFile2', 'readSet', 'refUmiFiles', 'roiBedFile', 'runCNV', 'sampleType', 'samtoolsDir', 'samtoolsMem', 'snpEffConfig', 'snpEffData', 'snpEffPath', 'sswPyFile', 'tagNameDuplex', 'tagNamePrimer', 'tagNamePrimerErr', 'tagNameResample', 'tagNameUmi', 'tagNameUmiSeq', 'torrentBinDir', 'tumorPurity', 'umiCutoff', 'vcfComplexGapMax', 'vcflibDir']
```
in ```core.tumor_normal.tumorNormalVarFilter(cfg)```

```
def tumorNormalVarFilter(cfg):
    ''' Filter Tumor variants
    '''
    readSetNormal =  cfg.readSetMatchedNormal
    readSetTumor  =  cfg.readSet
    ......
```
I couldn't figure out how this "readSetMatchedNormal" could get into ```cfg``` object with readSet 'tumor'.

Is there something wrong with my configure file (please see it below)? 
```
[general]
# tools
cutadaptDir = /opt/conda/bin/
bwaDir      = /opt/conda/bin/
samtoolsDir = /srv/qgen/bin/samtools-1.5/bin/
javaExe     = /opt/conda/jre/bin/java

# ssw for fast Smith-Waterman
sswPyFile = /srv/qgen/bin/ssw/src/ssw_wrap.py

# Ion torrent tools
torrentBinDir = /srv/qgen/bin/TorrentSuite/
vcflibDir = /srv/qgen/bin/vcflib/bin/

# quandico
quandicoDir = /srv/qgen/code/qiaseq-dna/quandico/

# general params
numCores = 4
deleteLocalFiles = False
samtoolsMem = 2500M
outputDetail = True

# prep module - read preparation (common region trimming) params
primer3Bases  = 8

-----------------------------------
# geneome file
genomeFile = /srv/qgen/example/genome/ucsc.hg19.fa

# umi module
endogenousLenMin = 15

# SAM tag names
tagNameUmiSeq    = mi
tagNameUmi       = Mi
tagNameDuplex    = Du
tagNamePrimer    = pr
tagNamePrimerErr = pe
tagNameResample  = re

# variant primitive to complex conversion
vcfComplexGapMax = 3

# variant annotation
snpEffPath   = /opt/conda/share/snpeff-4.2-0/
snpEffConfig = /opt/conda/share/snpeff-4.2-0/snpEff.config
snpEffData   = /srv/qgen/data/annotation/snpEff/
dbSnpFile    = /srv/qgen/data/annotation/common_all_20160601.vcf.gz
cosmicFile   = /srv/qgen/data/annotation/CosmicAllMuts_v69_20140602.vcf.gz
clinVarFile  = /srv/qgen/data/annotation/clinvar_20160531.vcf.gz

# tumor-normal params
# umiCutoff not being used currently
umiCutoff = 10
pValCutoff = 0.01
tumorPurity  = 0.90

# variant caller parameters (these need a separate section)
[smCounter]
minBQ = 25
minMQ = 50
hpLen = 8
mismatchThr = 6.0
consThr = 0.8
minAltUMI = 3
maxAltAllele = 2
primerDist = 2
repBed = /srv/qgen/data/annotation/simpleRepeat.full.bed
srBed = /srv/qgen/data/annotation/SR_LC_SL.full.bed

# readSet
[tumor]
readFile1 = /srv/qgen/example/raw/OV_1580/OV_1580_L3_1.fq.gz
readFile2 = /srv/qgen/example/raw/OV_1580/OV_1580_L3_2.fq.gz
instrument = HiSeqX
primerFile = /srv/qgen/example/reference/DHS-3501Z.primer3.txt
roiBedFile = /srv/qgen/example/reference/DHS-3501Z.roi.srt.bed
platform = Illumina
runCNV = True
sampleType =  tumor
duplex = False
refUmiFiles = /srv/qgen/code/qiaseq-dna/{N_1580}.sum.primer.umis.txt

# readSet
[normal]
readFile1 = /srv/qgen/example/raw/N_1580/N_1580_L3_1.fq.gz
readFile2 = /srv/qgen/example/raw/N_1580/N_1580_L3_2.fq.gz
instrument = HiSeqX
primerFile = /srv/qgen/example/reference/DHS-3501Z.primer3.txt
roiBedFile = /srv/qgen/example/reference/DHS-3501Z.roi.srt.bed
platform = Illumina
runCNV = False
sampleType =  normal
duplex = False
```
-----------------------------------

Thank you in advance for your help!
-Lei

**Comment by rpadmanabhan** [comment]
Hi Sorry about that, we use this pipeline internally and readSetMatchedNormal was a variable in the config file being used. I agree this is confusing since it is not documented anywhere and the normal sample is specified on the command line. I removed this parameter. 

Could you pull the master branch and try again ?

Thanks

**Comment by lxhuang7** [comment]
It works now. Thank you so much Raghavendra!
