### ISSUE TITLE
Error when parsing smCounter all.txt file

### ISSUE THREAD

**Issue by lxhuang7** [qiaseq/qiaseq-dna#35]
Hi Raghavendra,

I encountered another error when parsing normal.smCounter all.txt file for variant filtering:

```
2019-04-27 23:34:48.402 tumor_normal: Started filtering Tumor variants
2019-04-27 23:35:08.243 Traceback (most recent call last):
2019-04-27 23:35:08.243   File "/srv/qgen/code/qiaseq-dna/run_qiaseq_dna.py", line 201, in <module>
2019-04-27 23:35:08.244 run_tumor_normal(readSet,paramFile,vc)
2019-04-27 23:35:08.244   File "/srv/qgen/code/qiaseq-dna/run_qiaseq_dna.py", line 160, in run_tumor_normal
2019-04-27 23:35:08.244 core.tumor_normal.tumorNormalVarFilter(cfg, normal, tumor)
2019-04-27 23:35:08.245   File "/srv/qgen/code/qiaseq-dna/core/tumor_normal.py", line 335, in tumorNormalVarFilter
2019-04-27 23:35:08.247 normalAllVars, normalHomRefVars = parseSmCounterAllFile(readSetNormal)
2019-04-27 23:35:08.247   File "/srv/qgen/code/qiaseq-dna/core/tumor_normal.py", line 117, in parseSmCounterAllFile
2019-04-27 23:35:08.257 sVMF = float(sVMF)/100
2019-04-27 23:35:08.258 ValueError
2019-04-27 23:35:08.258 :
2019-04-27 23:35:08.259 could not convert string to float: .
```
It turned out one variant in normal sample normal.smCounter all.txt file has the sVMF value set as ".", that causes the following code in core/tumor_normal.py to fail:

```
def parseSmCounterAllFile(readSet):
    ...
    sVMF = float(sVMF)/100
    ...
```
CHROM | POS | REF | ALT | TYPE | sUMT | sForUMT | sRevUMT | sVMT | sForVMT | sRevVMT | sVMF | sForVMF | sRevVMF | VDP | VAF | RefForPrimer | RefRevPrimer | primerOR | pLowQ | hqUmiEff | allUmiEff | refMeanRpb | altMeanRpb | rpbEffectSize | repType | hpInfo | simpleRepeatInfo | tandemRepeatInfo | DP | FR | MT | UFR | sUMT_A | sUMT_T | sUMT_G | sUMT_C | logpval | FILTER
----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | -----
chr15 | 40994001 | G | A | SNP | 0 | 0 | 0 | 0 | 0 | 0 | . | . | . | 0 | 0 | 0 | 0 | NA | NA | 0 | 0 | -1 | -1 | -1 | NA | . | . | . | 242 | 167 | 102 | 13 | 0 | 0 | 0 | 0 | 0 | PASS

Is there a way to avoid this error or the code has to be modified? Please note I processed nine pairs of tumor-normal samples, two have this issue.

Thanks in advance for your help!
-Lei

**Comment by rpadmanabhan** [comment]
Yes, looks like that case should be handled by the code, but it is not at the moment. I will update the code to handle this in a few days. Sorry for the trouble.

**Comment by lxhuang7** [comment]
Thank you! I'm looking forward to the fix.

**Comment by rpadmanabhan** [comment]
Hi Lei,
Could you pull the code and try again ?  I think it is okay to ignore these sites for Tumor Normal filtering as there is no UMI coverage (after some filtering during variant calling). I just made a single line change for this.

**Comment by lxhuang7** [comment]
Hi Raghavendra,

Thanks! I pulled the new commit and re-ran the analyses on the previous sample pair that has sites with zero UMI coverage and a sample pair that doesn't have site with zero UMI coverage. However both are failed with the following errors for tumor samples:

```
2019-05-02 18:05:36.472 Calculating p-values 2019-05-02 18:05:36.472528
2019-05-02 18:05:46.138 Traceback (most recent call last):
2019-05-02 18:05:46.138   File "/srv/qgen/code/qiaseq-dna/run_qiaseq_dna.py", line 201, in <module>
2019-05-02 18:05:46.139 run_tumor_normal(readSet,paramFile,vc)
2019-05-02 18:05:46.139   File "/srv/qgen/code/qiaseq-dna/run_qiaseq_dna.py", line 152, in run_tumor_normal
2019-05-02 18:05:46.140 run((tumor,paramFile,vc),tumorNormal=True)
2019-05-02 18:05:46.140   File "/srv/qgen/code/qiaseq-dna/run_qiaseq_dna.py", line 88, in run
2019-05-02 18:05:46.141 numVariants = core.sm_counter_wrapper.run(cfg, paramFile, vc)
2019-05-02 18:05:46.141   File "/srv/qgen/code/qiaseq-dna/core/sm_counter_wrapper.py", line 70, in run
2019-05-02 18:05:46.142 sm_counter_v2.run.main(cfgSmCounter)
2019-05-02 18:05:46.143   File "/srv/qgen/code/qiaseq-dna/qiaseq-smcounter-v2/run.py", line 173, in main
2019-05-02 18:05:46.144 subprocess.check_call(pValCmd, shell=True)
2019-05-02 18:05:46.144   File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
2019-05-02 18:05:46.145 raise CalledProcessError(retcode, cmd)
2019-05-02 18:05:46.146 subprocess
2019-05-02 18:05:46.146 .
2019-05-02 18:05:46.146 CalledProcessError
2019-05-02 18:05:46.147 :
2019-05-02 18:05:46.147 Command 'Rscript /srv/qgen/code/qiaseq-dna/qiaseq-smcounter-v2/get_pvalue.R /srv/qgen/data/annotation/bkg.error.v2.RData ./ intermediate/noThres.tumor.VariantList.long.txt intermediate/bkg.tumor.txt 10262016 5000 intermediate/tumor.VariantList.long.txt intermediate/tumor.umi_depths.lod.bedgraph tumor 3.2 3 none' returned non-zero exit status 1
```

It looks like the file /srv/qgen/data/annotation/bkg.error.v2.RData cannot be found when executing get_pvalue.R R script:

```
root@671238ce9c8d:/data/output/VAN85# ll /srv/qgen/data/annotation/bkg.error.v2.RData
ls: cannot access '/srv/qgen/data/annotation/bkg.error.v2.RData': No such file or directory
```
Any idea?

Thanks again,
Lei

**Comment by rpadmanabhan** [comment]
Hmm thats weird since you had run some samples before without this error. Are you sure the data directory is mounted correctly on the container ?
You need to mount this directory (after getting it locally) :  gs://qiaseq-dna/data to /srv/qgen/data

**Comment by lxhuang7** [comment]
Ahh, that's the problem. Thanks for pointing this out! I'll fix it and try again.
Best,
Lei

**Comment by lxhuang7** [comment]
Thanks Raghavendra! The pipeline works without error now.
