### ISSUE TITLE
during umi_filter step "< 50 on-target read fragments found for read set"

### ISSUE THREAD

**Issue by Blowfish82** [qiaseq/qiaseq-dna#45]
Hi,

when trying to process paired fastq files, I get the following warning:

```
2019-09-19 12:14:10.714 prep: done
2019-09-19 12:14:10.714 align: starting read alignment
2019-09-19 12:17:27.464 align: done aligning reads to genome, bam file: NG-17071_42.align.bam
2019-09-19 12:17:27.464 umi_filter: starting...
2019-09-19 12:17:27.465 ('# of primers:', 308)
2019-09-19 12:18:27.495 Traceback (most recent call last):
2019-09-19 12:18:27.495   File "/srv/qgen/code/run_qiaseq_dna.py", line 203, in <module>
2019-09-19 12:18:27.495 run((readSet,paramFile,vc),tumorNormal = False)
2019-09-19 12:18:27.495   File "/srv/qgen/code/run_qiaseq_dna.py", line 57, in run
2019-09-19 12:18:27.495 core.umi_filter.run(cfg, bamFileIn)
2019-09-19 12:18:27.495   File "/srv/qgen/code/core/umi_filter.py", line 380, in run
2019-09-19 12:18:27.495 raise UserWarning("< 5 percent or < 50 on-target read fragments found for read set: {}".format(readSet))
2019-09-19 12:18:27.495 UserWarning
2019-09-19 12:18:27.495 :
2019-09-19 12:18:27.495 < 5 percent or < 50 on-target read fragments found for read set: NG-17071_42
```

Any idea what caused the error?
Many thanks for help.

**Comment by rpadmanabhan** [comment]
Sorry for the late response, this usually happens when primers were not correctly identified on the read.
This could be either because there was some oligo before the primer on R1. The trimmer should handle Illumina Sequencing Adapter before the primer. It can also be because of the primer file not being correctly specified.
